import Head from 'next/head';
import NavBar from '../components/nav/navbar';
import Banner from "../components/banner/banner";
import styles from '@/styles/Home.module.css';


export default function Home() {
  return (
    <>
      <Head>
        <title>Villa Tramonto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main} >
        < NavBar />
        <Banner
            title='Villa Tramonto'
            subTitle='Proporcionando conforto e tranquilidade para sua estadia'
            imgUrl='/static/VTentrada.jpeg'
          />
        {/** Card */}
      </div>
    </>
  )
}
